### PR TITLE
added 404 resource not found

### PR DESCRIPTION
**Pull request by seantdg**
Added tests and implementation for generic 404 Resource Not Found

Please note: tests for Payment API 404 will created along with the rest of the Payment API tests.

### CODE REVIEW

**Comment by seantdg** [comment]
I signed the CLA

**Comment by rohan-m** [comment]
Hey @seantdg 

The pull request looks good. 
Can we change the pull request to rev/v1.0.0 instead of master 

This way we can merge into master with a new release.
It will also be helpful for checks and testing before committing to master.
Please let me know your views on the same.

@malagappan @ksprashu Please advise

**Comment by malagappan** [comment]
Sounds good, Rohan.  Lets merge the change in v1.0.0, so that it will be available as part of the next release.

**Comment by laughingbiscuit** [comment]
closing

**Pull request closed without merging**
